name: Primal Ape Crossfit
favicon: null
layout_spectrum: 0.50577
typography_spectrum: 0.37117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060808'
    - '#fdcf00'
    - '#ffffff'
    - '#706a1a'
    - '#859494'
  brandStrength: 0.3133627469651401
  lightness: 0.975810480536893
  saturation: 0.8727304255589843
  rhythmicContrast: 0.6023189772386104
purpose: []
