name: Primal Ape Crossfit
favicon: null
layout_spectrum: 0.8066657078452408
typography_spectrum: 0.17633157316595316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3133627469651401
  lightness: 0.975810480536893
  saturation: 0.8727304255589843
  rhythmicContrast: 0.6023189772386104
purpose: []
